In [4]:
#1.Write  a  NumPy  program  to  create  an  element-wise  comparison  (greater,  greater_equal,  less and less_equal) of two given arrays
import numpy
x = numpy.array([3, 7, 6])
y = numpy.array([1, 5, 2])
print("Original arrays:")
print(x)
print(y)
print("Comparison")
print("--------Greater--------")
print(numpy.greater(x, y))
print("--------Greater_equal--------")
print(numpy.greater_equal(x, y))
print("--------Less--------")
print(numpy.less(x, y))
print("--------Less_equal--------")
print(numpy.less_equal(x, y))

Original arrays:
[3 7 6]
[1 5 2]
Comparison
--------Greater--------
[ True  True  True]
--------Greater_equal--------
[ True  True  True]
--------Less--------
[False False False]
--------Less_equal--------
[False False False]


In [5]:
#2.Write a NumPy program to create an array of all the even integers from 30 to 70

import numpy
arr=numpy.arange(30,71,2)
print("Array of all even numbers from 30 to 70")
print(arr) 

Array of all even numbers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [6]:
#3.Write a NumPy program to create a 3x3 identity matrix.

import numpy
arr=numpy.identity(3)
print("--------3x3 Matrix--------")
print(arr)

--------3x3 Matrix--------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
#4.Write  a  NumPy  program  to  create  a  vector  with  values from  0  to  20 and  change  the  sign  of the numbers in the range from 9 to 15

import numpy
arr=numpy.arange(21)
print("Original Vector:")
print(arr)
arr1=[i for i in arr if i<9]
arr2=[-i for i in arr if i>=9 and i<=15]
arr3=[i for i in arr if i>15]
arr1.extend(arr2)
arr1.extend(arr3)
print("Modified Vector:")
print(arr1)

Original Vector:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Modified Vector:
[0, 1, 2, 3, 4, 5, 6, 7, 8, -9, -10, -11, -12, -13, -14, -15, 16, 17, 18, 19, 20]


In [8]:
#5.Write  a  NumPy  program  to  create  a  5x5  zero  matrix  with  elements  on  the  main  diagonal equal to 1, 2, 3, 4, 5

import numpy
x = numpy.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [9]:
#6.Write  a  NumPy  program  to  compute  sum  of  all  elements,  sum  of  each  column  and  sum  of each row of a given array

import numpy
x = numpy.array([[15,24],[20,31]])
print("-------Original array-------")
print(x)
print("Sum of all elements:")
print(numpy.sum(x))
print("Sum of each column:")
print(numpy.sum(x, axis=0))
print("Sum of each row:")
print(numpy.sum(x, axis=1))


-------Original array-------
[[15 24]
 [20 31]]
Sum of all elements:
90
Sum of each column:
[35 55]
Sum of each row:
[39 51]


In [21]:
#7.Write a NumPy program to save a given array to a text file and load it.

import numpy
arr=numpy.array([1,2,3,4])
print("Original array:")
print(arr)
numpy.savetxt("file2.txt",arr)
contents=numpy.loadtxt("file2.txt")
print("File contents:")
print(contents)

Original array:
[1 2 3 4]
File contents:
[1. 2. 3. 4.]


In [20]:
#8.Write a NumPy program to check whether two arrays are equal (element wise) or not

import numpy
arr1 = numpy.array([2,4,5,6])
arr2 = numpy.array([8,4,5,9])
print("Original arrays:")
print(arr1)
print(arr2)
print("\nTwo arrays are equal (element wise) or not?")
print(arr1 == arr2)

Original arrays:
[2 4 5 6]
[8 4 5 9]

Two arrays are equal (element wise) or not?
[False  True  True False]


In [19]:
#9.Write  a  NumPy  program  to  create  a  4x4  array  with  random  values,  now  create  a  new  array from the said array swapping first and last rows.
import numpy 
arr1 = numpy.arange(16).reshape(4, 4)
print("Original array:")
print(arr1)
print("\n Array after swapping first and last rows:")
arr1[[0,3]]=arr1[[3,0]]
print(arr1)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 Array after swapping first and last rows:
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [18]:
#10.Write a NumPy program to multiply two given arrays of same size element-by-element.

import numpy
arr1 = numpy.array([[1, 2, 3],
              [4, 5, 6]])
arr2 = numpy.array([[5, 1, 4],
              [2, 2, 1]])
print("Array1:") 
print(arr1)
print("Array2:") 
print(arr2)
print("\nMultiplying Array1 and Array2 element by element:")
print(numpy.multiply(arr1, arr2))

Array1:
[[1 2 3]
 [4 5 6]]
Array2:
[[5 1 4]
 [2 2 1]]

Multiplying Array1 and Array2 element by element:
[[ 5  2 12]
 [ 8 10  6]]
